-- Create the database
-- DROP DATABASE BookFlights
-- DROP TABLE Bookings
--CREATE DATABASE BookFlights1;
--GO

USE BookFlights1
CREATE TABLE Flights (
    FlightID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    FlightNumber VARCHAR(10) NOT NULL,
    DepartureAirport VARCHAR(100) NOT NULL,
    ArrivalAirport VARCHAR(100) NOT NULL,
    DepartureTime DATETIME NOT NULL,
    ArrivalTime DATETIME NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    SeatsAvailable INT NOT NULL,
	 CreatedAt DATETIME DEFAULT GETDATE(),
	 ModifyAt DATETIME DEFAULT GETDATE(),
	 UpdateId NVARCHAR(200) NOT NULL,
	CreateId NVARCHAR(200) NOT NULL
);
-- DROP TABLE Bookings
CREATE TABLE Bookings (
    BookingID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID() ,
    FlightID INT NOT NULL,
    CustomerName VARCHAR(100) NOT NULL,
    CustomerEmail VARCHAR(100) NOT NULL,
    BookingDate DATETIME NOT NULL DEFAULT GETDATE(),
    SeatsBooked INT NOT NULL,
	 CreatedAt DATETIME DEFAULT GETDATE(),
	 ModifyAt DATETIME DEFAULT GETDATE(),
	 UpdateId NVARCHAR(200) NOT NULL,
	CreateId NVARCHAR(200) NOT NULL
);


-- DROP TABLE Payments
CREATE TABLE Payments (
    PaymentID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    BookingID INT NOT NULL,
    PaymentDate DATETIME NOT NULL DEFAULT GETDATE(),
    Amount DECIMAL(10, 2) NOT NULL,
    PaymentMethod VARCHAR(50) NOT NULL,
    PaymentStatus VARCHAR(20) NOT NULL,
	 CreatedAt DATETIME DEFAULT GETDATE(),
	 ModifyAt DATETIME DEFAULT GETDATE(),
	 UpdateId NVARCHAR(200) NOT NULL,
	CreateId NVARCHAR(200) NOT NULL
);

-- DROP TABLE BookingHistory
CREATE TABLE BookingHistory (
    HistoryID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID() ,
    BookingID INT NOT NULL,
    ChangeDate DATETIME NOT NULL DEFAULT GETDATE(),
    ChangeDescription VARCHAR(255) NOT NULL,
	 CreatedAt DATETIME DEFAULT GETDATE(),
	 ModifyAt DATETIME DEFAULT GETDATE(),
	 UpdateId NVARCHAR(200) NOT NULL,
	CreateId NVARCHAR(200) NOT NULL
);

CREATE TABLE Users (
    UserID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
	[Password] NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) UNIQUE NOT NULL,
    PhoneNumber NVARCHAR(15),
    CreatedAt DATETIME DEFAULT GETDATE()
);
